<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>OrdenaPC</AssemblyName>
    <RootNamespace>OrdenaPC</RootNamespace>
    <Version>0.1.0</Version>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrdenaPC.Core\OrdenaPC.Core.csproj" />
  </ItemGroup>
</Project>
